name: itsypad
options:
  bundleIdPrefix: com.nickustinov
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: false

settings:
  base:
    DEVELOPMENT_TEAM: R892A93W42
    CODE_SIGN_STYLE: Automatic
    CODE_SIGN_IDENTITY: "Apple Development"

packages:
  Bonsplit:
    path: Packages/Bonsplit

targets:
  itsypad:
    type: application
    platform: macOS
    sources:
      - path: Sources
        excludes:
          - Info.plist
          - itsypad.entitlements
      - path: Executable
    dependencies:
      - package: Bonsplit
        product: Bonsplit
    info:
      path: Sources/Info.plist
      properties:
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        NSPrincipalClass: NSApplication
        CFBundleDocumentTypes:
          - CFBundleTypeName: All Files
            CFBundleTypeRole: Editor
            LSHandlerRank: Alternate
            LSItemContentTypes:
              - public.data
              - public.plain-text
              - public.source-code
              - public.text
              - public.content
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.nickustinov.itsypad
        PRODUCT_NAME: Itsypad
        PRODUCT_MODULE_NAME: ItsypadCore
        MARKETING_VERSION: "1.3.1"
        CURRENT_PROJECT_VERSION: "131"
        CODE_SIGN_ENTITLEMENTS: Sources/itsypad.entitlements
        CODE_SIGN_ALLOW_ENTITLEMENTS_MODIFICATION: true
        SWIFT_VERSION: "5.9"
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        LD_RUNPATH_SEARCH_PATHS: "@executable_path/../Frameworks"
        ENABLE_HARDENED_RUNTIME: true
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon

  ItsypadTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: Tests
    dependencies:
      - target: itsypad
    settings:
      base:
        SWIFT_VERSION: "5.9"
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        GENERATE_INFOPLIST_FILE: true
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Itsypad.app/Contents/MacOS/Itsypad"
        BUNDLE_LOADER: "$(TEST_HOST)"
