name: itsypad
options:
  bundleIdPrefix: com.nickustinov
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: false

configs:
  Debug: debug
  Debug-AppStore: debug
  Release: release
  Release-AppStore: release

settings:
  base:
    DEVELOPMENT_TEAM: R892A93W42
    CODE_SIGN_STYLE: Automatic
    CODE_SIGN_IDENTITY: "Apple Development"

packages:
  Bonsplit:
    path: Packages/Bonsplit

schemes:
  itsypad:
    build:
      targets:
        itsypad: all
        ItsypadTests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - ItsypadTests
    archive:
      config: Release
  itsypad-appstore:
    build:
      targets:
        itsypad: all
    run:
      config: Debug-AppStore
    test:
      config: Debug-AppStore
    archive:
      config: Release-AppStore

targets:
  itsypad:
    type: application
    platform: macOS
    sources:
      - path: Sources
        excludes:
          - Info.plist
          - itsypad.entitlements
          - itsypad-direct.entitlements
      - path: Executable
    dependencies:
      - package: Bonsplit
        product: Bonsplit
    info:
      path: Sources/Info.plist
      properties:
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        NSPrincipalClass: NSApplication
        LSApplicationCategoryType: public.app-category.productivity
        ITSAppUsesNonExemptEncryption: false
        CFBundleDocumentTypes:
          - CFBundleTypeName: All Files
            CFBundleTypeRole: Editor
            LSHandlerRank: Alternate
            LSItemContentTypes:
              - public.data
              - public.plain-text
              - public.source-code
              - public.text
              - public.content
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.nickustinov.itsypad
        PRODUCT_NAME: Itsypad
        PRODUCT_MODULE_NAME: ItsypadCore
        MARKETING_VERSION: "1.7.1"
        CURRENT_PROJECT_VERSION: "171"
        CODE_SIGN_ENTITLEMENTS: Sources/itsypad.entitlements
        CODE_SIGN_ALLOW_ENTITLEMENTS_MODIFICATION: true
        SWIFT_VERSION: "5.9"
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        LD_RUNPATH_SEARCH_PATHS: "@executable_path/../Frameworks"
        ENABLE_HARDENED_RUNTIME: true
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        INFOPLIST_KEY_CFBundleDisplayName: Itsypad
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.productivity
      configs:
        Debug:
          CODE_SIGN_ENTITLEMENTS: Sources/itsypad-direct.entitlements
        Release:
          CODE_SIGN_ENTITLEMENTS: Sources/itsypad-direct.entitlements
        Debug-AppStore:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: APPSTORE
        Release-AppStore:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: APPSTORE

  ItsypadTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: Tests
    dependencies:
      - target: itsypad
    settings:
      base:
        SWIFT_VERSION: "5.9"
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        GENERATE_INFOPLIST_FILE: true
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Itsypad.app/Contents/MacOS/Itsypad"
        BUNDLE_LOADER: "$(TEST_HOST)"
